### ISSUE TITLE
Add a message to Findings

### ISSUE THREAD

**Issue by thombergs** [adessoAG/coderadar#14]
Findings should be able to store a localized message to be displayed in the code review where findings are marked.

**Comment by maximAtanasov** [comment]
I think we could write and attach messages to the metrics. For example:
`IndentationCheck` could be mapped to `This line/block of code is not properly indented` or some other more descriptive message better suited for displaying to the user.

**Comment by KilianKrause** [comment]
@maximAtanasov I agree with you.

**Comment by maximAtanasov** [comment]
Closed in #356
