### ISSUE TITLE
Blocks representing deleted files in the 3D view are displayed outside of the main area

### ISSUE THREAD

**Issue by maximAtanasov** [adessoAG/coderadar#316]
Screenshot:

![grafik](https://user-images.githubusercontent.com/32562426/73064727-2b483d00-3ea2-11ea-9136-8f7e26bc0c40.png)

**Comment by LauchInterceptor** [comment]
Can I close an issue when it is fixed but not yet in the main codebase?

**Comment by maximAtanasov** [comment]
We generally close an issue when the fix is merged into master.

**Comment by maximAtanasov** [comment]
What's the progress on this issue?

**Comment by LauchInterceptor** [comment]
This issue is fixed in the linked PR.
